JEIEvents.hideItems(event => // changed onEvent here
{
    event.hide('minecraft:copper_ingot')
    event.hide('minecraft:iron_ingot')
    event.hide('minecraft:gold_ingot')
    event.hide('minecraft:netherite_helmet')
    event.hide('minecraft:netherite_chestplate')
    event.hide('create:crushed_raw_silver')
    event.hide('create:crushed_raw_tin')
    event.hide('create:crushed_raw_nickel')
    event.hide('create:zinc_ingot')
    event.hide('create:brass_ingot')
    event.hide('create:copper_sheet')
    event.hide('create:brass_sheet')
    event.hide('create:iron_sheet')
    event.hide('create:golden_sheet')

    event.hide('create:empty_blaze_burner')
    event.hide('create:blaze_cake')
    // event.hide('tfc:food/dried_kelp')
    event.hide('kubejs:incomplete_brass_mechanisms')
    
    event.hide('kubejs:incomplete_circular_saw')

    // added to this list by Infinity_Broken
    event.hide('minecraft:oak_wood')
    event.hide('minecraft:oak_log')
    event.hide('minecraft:stripped_oak_log')
    event.hide('minecraft:stripped_oak_wood')
    event.hide('minecraft:oak_planks')
    event.hide('minecraft:oak_stairs')
    event.hide('minecraft:oak_slab')
    event.hide('minecraft:oak_fence')
    event.hide('minecraft:oak_fence_gate')
    event.hide('minecraft:oak_door')
    event.hide('minecraft:oak_trapdoor')
    event.hide('minecraft:oak_pressure_plate')
    event.hide('minecraft:oak_button')
    event.hide('minecraft:oak_leaves')
    event.hide('minecraft:oak_sapling')
    event.hide('minecraft:oak_sign')
    event.hide('minecraft:oak_hanging_sign')
    event.hide('minecraft:oak_boat')
    event.hide('minecraft:oak_chest_boat')

    event.hide('minecraft:spruce_wood')
    event.hide('minecraft:spruce_log')
    event.hide('minecraft:stripped_spruce_log')
    event.hide('minecraft:stripped_spruce_wood')
    event.hide('minecraft:spruce_planks')
    event.hide('minecraft:spruce_stairs')
    event.hide('minecraft:spruce_slab')
    event.hide('minecraft:spruce_fence')
    event.hide('minecraft:spruce_fence_gate')
    event.hide('minecraft:spruce_door')
    event.hide('minecraft:spruce_trapdoor')
    event.hide('minecraft:spruce_pressure_plate')
    event.hide('minecraft:spruce_button')
    event.hide('minecraft:spruce_leaves')
    event.hide('minecraft:spruce_sapling')
    event.hide('minecraft:spruce_sign')
    event.hide('minecraft:spruce_hanging_sign')
    event.hide('minecraft:spruce_boat')
    event.hide('minecraft:spruce_chest_boat')

    event.hide('minecraft:birch_wood')
    event.hide('minecraft:birch_log')
    event.hide('minecraft:stripped_birch_log')
    event.hide('minecraft:stripped_birch_wood')
    event.hide('minecraft:birch_planks')
    event.hide('minecraft:birch_stairs')
    event.hide('minecraft:birch_slab')
    event.hide('minecraft:birch_fence')
    event.hide('minecraft:birch_fence_gate')
    event.hide('minecraft:birch_door')
    event.hide('minecraft:birch_trapdoor')
    event.hide('minecraft:birch_pressure_plate')
    event.hide('minecraft:birch_button')
    event.hide('minecraft:birch_leaves')
    event.hide('minecraft:birch_sapling')
    event.hide('minecraft:birch_sign')
    event.hide('minecraft:birch_hanging_sign')
    event.hide('minecraft:birch_boat')
    event.hide('minecraft:birch_chest_boat')

    event.hide('minecraft:jungle_wood')
    event.hide('minecraft:jungle_log')
    event.hide('minecraft:stripped_jungle_log')
    event.hide('minecraft:stripped_jungle_wood')
    event.hide('minecraft:jungle_planks')
    event.hide('minecraft:jungle_stairs')
    event.hide('minecraft:jungle_slab')
    event.hide('minecraft:jungle_fence')
    event.hide('minecraft:jungle_fence_gate')
    event.hide('minecraft:jungle_door')
    event.hide('minecraft:jungle_trapdoor')
    event.hide('minecraft:jungle_pressure_plate')
    event.hide('minecraft:jungle_button')
    event.hide('minecraft:jungle_leaves')
    event.hide('minecraft:jungle_sapling')
    event.hide('minecraft:jungle_sign')
    event.hide('minecraft:jungle_hanging_sign')
    event.hide('minecraft:jungle_boat')
    event.hide('minecraft:jungle_chest_boat')

    event.hide('minecraft:acacia_wood')
    event.hide('minecraft:acacia_log')
    event.hide('minecraft:stripped_acacia_log')
    event.hide('minecraft:stripped_acacia_wood')
    event.hide('minecraft:acacia_planks')
    event.hide('minecraft:acacia_stairs')
    event.hide('minecraft:acacia_slab')
    event.hide('minecraft:acacia_fence')
    event.hide('minecraft:acacia_fence_gate')
    event.hide('minecraft:acacia_door')
    event.hide('minecraft:acacia_trapdoor')
    event.hide('minecraft:acacia_pressure_plate')
    event.hide('minecraft:acacia_button')
    event.hide('minecraft:acacia_leaves')
    event.hide('minecraft:acacia_sapling')
    event.hide('minecraft:acacia_sign')
    event.hide('minecraft:acacia_hanging_sign')
    event.hide('minecraft:acacia_boat')
    event.hide('minecraft:acacia_chest_boat')

    event.hide('minecraft:dark_oak_wood')
    event.hide('minecraft:dark_oak_log')
    event.hide('minecraft:stripped_dark_oak_log')
    event.hide('minecraft:stripped_dark_oak_wood')
    event.hide('minecraft:dark_oak_planks')
    event.hide('minecraft:dark_oak_stairs')
    event.hide('minecraft:dark_oak_slab')
    event.hide('minecraft:dark_oak_fence')
    event.hide('minecraft:dark_oak_fence_gate')
    event.hide('minecraft:dark_oak_door')
    event.hide('minecraft:dark_oak_trapdoor')
    event.hide('minecraft:dark_oak_pressure_plate')
    event.hide('minecraft:dark_oak_button')
    event.hide('minecraft:dark_oak_leaves')
    event.hide('minecraft:dark_oak_sapling')
    event.hide('minecraft:dark_oak_sign')
    event.hide('minecraft:dark_oak_hanging_sign')
    event.hide('minecraft:dark_oak_boat')
    event.hide('minecraft:dark_oak_chest_boat')

    event.hide('minecraft:mangrove_wood')
    event.hide('minecraft:mangrove_log')
    event.hide('minecraft:stripped_mangrove_log')
    event.hide('minecraft:stripped_mangrove_wood')
    event.hide('minecraft:mangrove_planks')
    event.hide('minecraft:mangrove_stairs')
    event.hide('minecraft:mangrove_slab')
    event.hide('minecraft:mangrove_fence')
    event.hide('minecraft:mangrove_fence_gate')
    event.hide('minecraft:mangrove_door')
    event.hide('minecraft:mangrove_trapdoor')
    event.hide('minecraft:mangrove_pressure_plate')
    event.hide('minecraft:mangrove_button')
    event.hide('minecraft:mangrove_leaves')
    event.hide('minecraft:mangrove_propagule')
    event.hide('minecraft:mangrove_sign')
    event.hide('minecraft:mangrove_hanging_sign')
    event.hide('minecraft:mangrove_boat')
    event.hide('minecraft:mangrove_chest_boat')

    event.hide('minecraft:cherry_wood')
    event.hide('minecraft:cherry_log')
    event.hide('minecraft:stripped_cherry_log')
    event.hide('minecraft:stripped_cherry_wood')
    event.hide('minecraft:cherry_planks')
    event.hide('minecraft:cherry_stairs')
    event.hide('minecraft:cherry_slab')
    event.hide('minecraft:cherry_fence')
    event.hide('minecraft:cherry_fence_gate')
    event.hide('minecraft:cherry_door')
    event.hide('minecraft:cherry_trapdoor')
    event.hide('minecraft:cherry_pressure_plate')
    event.hide('minecraft:cherry_button')
    event.hide('minecraft:cherry_leaves')
    event.hide('minecraft:cherry_sapling')
    event.hide('minecraft:cherry_sign')
    event.hide('minecraft:cherry_hanging_sign')
    event.hide('minecraft:cherry_boat')
    event.hide('minecraft:cherry_chest_boat')

    event.hide('minecraft:bamboo_block')
    event.hide('minecraft:stripped_bamboo_block')
    event.hide('minecraft:bamboo_planks')
    event.hide('minecraft:bamboo_mosaic')
    event.hide('minecraft:bamboo_stairs')
    event.hide('minecraft:bamboo_mosaic_stairs')
    event.hide('minecraft:bamboo_slab')
    event.hide('minecraft:bamboo_mosaic_slab')
    event.hide('minecraft:bamboo_fence')
    event.hide('minecraft:bamboo_fence_gate')
    event.hide('minecraft:bamboo_door')
    event.hide('minecraft:bamboo_trapdoor')
    event.hide('minecraft:bamboo_pressure_plate')
    event.hide('minecraft:bamboo_button')
    event.hide('minecraft:bamboo_sign')
    event.hide('minecraft:bamboo_hanging_sign')
    event.hide('minecraft:bamboo_raft')
    event.hide('minecraft:bamboo_chest_boat')

    event.hide('minecraft:crimson_stem')
    event.hide('minecraft:crimson_hyphae')
    event.hide('minecraft:stripped_crimson_stem')
    event.hide('minecraft:stripped_crimson_hyphae')
    event.hide('minecraft:crimson_planks')
    event.hide('minecraft:crimson_stairs')
    event.hide('minecraft:crimson_slab')
    event.hide('minecraft:crimson_fence')
    event.hide('minecraft:crimson_fence_gate')
    event.hide('minecraft:crimson_door')
    event.hide('minecraft:crimson_trapdoor')
    event.hide('minecraft:crimson_pressure_plate')
    event.hide('minecraft:crimson_button')
    event.hide('minecraft:crimson_sign')
    event.hide('minecraft:crimson_hanging_sign')

    event.hide('minecraft:warped_stem')
    event.hide('minecraft:warped_hyphae')
    event.hide('minecraft:stripped_warped_stem')
    event.hide('minecraft:stripped_warped_hyphae')
    event.hide('minecraft:warped_planks')
    event.hide('minecraft:warped_stairs')
    event.hide('minecraft:warped_slab')
    event.hide('minecraft:warped_fence')
    event.hide('minecraft:warped_fence_gate')
    event.hide('minecraft:warped_door')
    event.hide('minecraft:warped_trapdoor')
    event.hide('minecraft:warped_pressure_plate')
    event.hide('minecraft:warped_button')
    event.hide('minecraft:warped_sign')
    event.hide('minecraft:warped_hanging_sign')


    event.hide('minecraft:stone')
    event.hide('minecraft:stone_stairs')
    event.hide('minecraft:stone_slab')
    event.hide('minecraft:stone_pressure_plate')
    event.hide('minecraft:stone_button')

    event.hide('minecraft:cobblestone')
    event.hide('minecraft:cobblestone_stairs')
    event.hide('minecraft:cobblestone_slab')
    event.hide('minecraft:cobblestone_wall')

    event.hide('minecraft:mossy_cobblestone')
    event.hide('minecraft:mossy_cobblestone_stairs')
    event.hide('minecraft:mossy_cobblestone_slab')
    event.hide('minecraft:mossy_cobblestone_wall')

    event.hide('minecraft:smooth_stone')
    event.hide('minecraft:smooth_stone_slab')

    event.hide('minecraft:stone_bricks')
    event.hide('minecraft:cracked_stone_bricks')
    event.hide('minecraft:stone_brick_stairs')
    event.hide('minecraft:stone_brick_slab')
    event.hide('minecraft:stone_brick_wall')
    event.hide('minecraft:chiseled_stone_bricks')

    event.hide('minecraft:mossy_stone_bricks')
    event.hide('minecraft:mossy_stone_brick_stairs')
    event.hide('minecraft:mossy_stone_brick_slab')
    event.hide('minecraft:mossy_stone_brick_wall')

    event.hide('minecraft:granite')
    event.hide('minecraft:granite_stairs')
    event.hide('minecraft:granite_slab')
    event.hide('minecraft:granite_wall')
    event.hide('minecraft:polished_granite')
    event.hide('minecraft:polished_granite_stairs')
    event.hide('minecraft:polished_granite_slab')

    event.hide('minecraft:diorite')
    event.hide('minecraft:diorite_stairs')
    event.hide('minecraft:diorite_slab')
    event.hide('minecraft:diorite_wall')
    event.hide('minecraft:polished_diorite')
    event.hide('minecraft:polished_diorite_stairs')
    event.hide('minecraft:polished_diorite_slab')

    event.hide('minecraft:andesite')
    event.hide('minecraft:andesite_stairs')
    event.hide('minecraft:andesite_slab')
    event.hide('minecraft:andesite_wall')
    event.hide('minecraft:polished_andesite')
    event.hide('minecraft:polished_andesite_stairs')
    event.hide('minecraft:polished_andesite_slab')

    event.hide('minecraft:deepslate')
    event.hide('minecraft:cobbled_deepslate')
    event.hide('minecraft:cobbled_deepslate_stairs')
    event.hide('minecraft:cobbled_deepslate_slab')
    event.hide('minecraft:cobbled_deepslate_wall')
    event.hide('minecraft:chiseled_deepslate')
    event.hide('minecraft:polished_deepslate')
    event.hide('minecraft:polished_deepslate_stairs')
    event.hide('minecraft:polished_deepslate_slab')
    event.hide('minecraft:polished_deepslate_wall')
    event.hide('minecraft:deepslate_bricks')
    event.hide('minecraft:cracked_deepslate_bricks')
    event.hide('minecraft:deepslate_brick_stairs')
    event.hide('minecraft:deepslate_brick_slab')
    event.hide('minecraft:deepslate_brick_wall')
    event.hide('minecraft:deepslate_tiles')
    event.hide('minecraft:cracked_deepslate_tiles')
    event.hide('minecraft:deepslate_tile_stairs')
    event.hide('minecraft:deepslate_tile_slab')
    event.hide('minecraft:deepslate_tile_wall')
    event.hide('minecraft:reinforced_deepslate')

    event.hide('minecraft:bricks')
    event.hide('minecraft:brick_stairs')
    event.hide('minecraft:brick_slab')
    event.hide('minecraft:brick_wall')

    event.hide('minecraft:packed_mud')
    event.hide('minecraft:mud_bricks')
    event.hide('minecraft:mud_brick_stairs')
    event.hide('minecraft:mud_brick_slab')
    event.hide('minecraft:mud_brick_wall')

    event.hide('minecraft:sandstone')
    event.hide('minecraft:sandstone_stairs')
    event.hide('minecraft:sandstone_slab')
    event.hide('minecraft:sandstone_wall')
    event.hide('minecraft:chiseled_sandstone')
    event.hide('minecraft:smooth_sandstone')
    event.hide('minecraft:smooth_sandstone_stairs')
    event.hide('minecraft:smooth_sandstone_slab')
    event.hide('minecraft:cut_sandstone')
    event.hide('minecraft:cut_sandstone_slab')

    event.hide('minecraft:red_sandstone')
    event.hide('minecraft:red_sandstone_stairs')
    event.hide('minecraft:red_sandstone_slab')
    event.hide('minecraft:red_sandstone_wall')
    event.hide('minecraft:chiseled_red_sandstone')
    event.hide('minecraft:smooth_red_sandstone')
    event.hide('minecraft:smooth_red_sandstone_stairs')
    event.hide('minecraft:smooth_red_sandstone_slab')
    event.hide('minecraft:cut_red_sandstone')
    event.hide('minecraft:cut_red_sandstone_slab')

    event.hide('minecraft:sea_lantern')
    event.hide('minecraft:prismarine')
    event.hide('minecraft:prismarine_stairs')
    event.hide('minecraft:prismarine_slab')
    event.hide('minecraft:prismarine_wall')
    event.hide('minecraft:prismarine_bricks')
    event.hide('minecraft:prismarine_brick_stairs')
    event.hide('minecraft:prismarine_brick_slab')
    event.hide('minecraft:dark_prismarine')
    event.hide('minecraft:dark_prismarine_stairs')
    event.hide('minecraft:dark_prismarine_slab')

    event.hide('minecraft:netherrack')
    event.hide('minecraft:nether_bricks')
    event.hide('minecraft:cracked_nether_bricks')
    event.hide('minecraft:nether_brick_stairs')
    event.hide('minecraft:nether_brick_slab')
    event.hide('minecraft:nether_brick_wall')
    event.hide('minecraft:nether_brick_fence')
    event.hide('minecraft:chiseled_nether_bricks')
    event.hide('minecraft:red_nether_bricks')
    event.hide('minecraft:red_nether_brick_stairs')
    event.hide('minecraft:red_nether_brick_slab')
    event.hide('minecraft:red_nether_brick_wall')

    event.hide('minecraft:basalt')
    event.hide('minecraft:smooth_basalt')
    event.hide('minecraft:polished_basalt')

    event.hide('minecraft:blackstone')
    event.hide('minecraft:gilded_blackstone')
    event.hide('minecraft:blackstone_stairs')
    event.hide('minecraft:blackstone_slab')
    event.hide('minecraft:blackstone_wall')
    event.hide('minecraft:chiseled_polished_blackstone')
    event.hide('minecraft:polished_blackstone')
    event.hide('minecraft:polished_blackstone_stairs')
    event.hide('minecraft:polished_blackstone_slab')
    event.hide('minecraft:polished_blackstone_wall')
    event.hide('minecraft:polished_blackstone_pressure_plate')
    event.hide('minecraft:polished_blackstone_button')
    event.hide('minecraft:polished_blackstone_bricks')
    event.hide('minecraft:cracked_polished_blackstone_bricks')
    event.hide('minecraft:polished_blackstone_brick_stairs')
    event.hide('minecraft:polished_blackstone_brick_slab')
    event.hide('minecraft:polished_blackstone_brick_wall')

    event.hide('minecraft:end_stone')
    event.hide('minecraft:end_stone_bricks')
    event.hide('minecraft:end_stone_brick_stairs')
    event.hide('minecraft:end_stone_brick_slab')
    event.hide('minecraft:end_stone_brick_wall')

    event.hide('minecraft:purpur_block')
    event.hide('minecraft:purpur_pillar')
    event.hide('minecraft:purpur_stairs')
    event.hide('minecraft:purpur_slab')

    event.hide('minecraft:iron_block')
    event.hide('minecraft:iron_bars')
    event.hide('minecraft:iron_door')
    event.hide('minecraft:iron_trapdoor')
    event.hide('minecraft:heavy_weighted_pressure_plate')
    event.hide('minecraft:iron_block')
    event.hide('minecraft:chain')
    event.hide('minecraft:gold_block')
    event.hide('minecraft:light_weighted_pressure_plate')
    event.hide('minecraft:emerald_block')
    event.hide('minecraft:diamond_block')
    event.hide('minecraft:netherite_block')

    event.hide('minecraft:amethyst_block')
    event.hide('minecraft:cobweb')

    event.hide('minecraft:shulker_box')
    event.hide('minecraft:white_shulker_box')
    event.hide('minecraft:light_gray_shulker_box')
    event.hide('minecraft:gray_shulker_box')
    event.hide('minecraft:black_shulker_box')
    event.hide('minecraft:brown_shulker_box')
    event.hide('minecraft:red_shulker_box')
    event.hide('minecraft:orange_shulker_box')
    event.hide('minecraft:yellow_shulker_box')
    event.hide('minecraft:lime_shulker_box')
    event.hide('minecraft:green_shulker_box')
    event.hide('minecraft:cyan_shulker_box')
    event.hide('minecraft:light_blue_shulker_box')
    event.hide('minecraft:blue_shulker_box')
    event.hide('minecraft:purple_shulker_box')
    event.hide('minecraft:magenta_shulker_box')
    event.hide('minecraft:pink_shulker_box')
    
    event.hide('minecraft:grass_block')
    event.hide('minecraft:podzol')
    event.hide('minecraft:mycelium')
    event.hide('minecraft:dirt_path')
    event.hide('minecraft:dirt')
    event.hide('minecraft:coarse_dirt')
    event.hide('minecraft:rooted_dirt')
    event.hide('minecraft:farmland')
    event.hide('minecraft:mud')

    event.hide('minecraft:gravel')
    event.hide('minecraft:sand')
    event.hide('minecraft:red_sand')
    event.hide('minecraft:ice')

    event.hide('minecraft:calcite')
    event.hide('minecraft:tuff')
    event.hide('minecraft:dripstone_block')
    event.hide('minecraft:pointed_dripstone')
    event.hide('minecraft:magma_block')
    event.hide('minecraft:crying_obsidian')
    event.hide('minecraft:crimson_nylium')
    event.hide('minecraft:warped_nylium')
    event.hide('minecraft:soul_sand')
    event.hide('minecraft:soul_soil')

    event.hide('minecraft:coal_ore')
    event.hide('minecraft:deepslate_coal_ore')
    event.hide('minecraft:iron_ore')
    event.hide('minecraft:deepslate_iron_ore')
    event.hide('minecraft:copper_ore')
    event.hide('minecraft:deepslate_copper_ore')
    event.hide('minecraft:gold_ore')
    event.hide('minecraft:deepslate_gold_ore')
    event.hide('minecraft:redstone_ore')
    event.hide('minecraft:deepslate_redstone_ore')
    event.hide('minecraft:emerald_ore')
    event.hide('minecraft:deepslate_emerald_ore')
    event.hide('minecraft:lapis_ore')
    event.hide('minecraft:deepslate_lapis_ore')
    event.hide('minecraft:diamond_ore')
    event.hide('minecraft:deepslate_diamond_ore')
    event.hide('minecraft:nether_gold_ore')
    event.hide('minecraft:nether_quartz_ore')
    event.hide('minecraft:ancient_debris')
    event.hide('minecraft:raw_iron_block')
    event.hide('minecraft:raw_copper_block')
    event.hide('minecraft:raw_gold_block')
    
    event.hide('minecraft:budding_amethyst')
    event.hide('minecraft:small_amethyst_bud')
    event.hide('minecraft:medium_amethyst_bud')
    event.hide('minecraft:large_amethyst_bud')
    event.hide('minecraft:amethyst_cluster')

    event.hide('minecraft:vine')
    event.hide('minecraft:kelp')
    event.hide('minecraft:mangrove_roots')
    event.hide('minecraft:muddy_mangrove_roots')
    event.hide('minecraft:mushroom_stem')
    event.hide('minecraft:brown_mushroom_block')
    event.hide('minecraft:red_mushroom_block')
    event.hide('minecraft:azalea_leaves')
    event.hide('minecraft:flowering_azalea_leaves')
    event.hide('minecraft:azalea')
    event.hide('minecraft:flowering_azalea')

    event.hide('minecraft:nether_wart_block')
    event.hide('minecraft:warped_wart_block')
    event.hide('minecraft:shroomlight')

    event.hide('minecraft:brown_mushroom')
    event.hide('minecraft:red_mushroom')
    event.hide('minecraft:crimson_fungus')
    event.hide('minecraft:warped_fungus')
    event.hide('minecraft:grass')
    event.hide('minecraft:fern')
    event.hide('minecraft:dead_bush')
    event.hide('minecraft:dandelion')
    event.hide('minecraft:poppy')
    event.hide('minecraft:blue_orchid')
    event.hide('minecraft:allium')
    event.hide('minecraft:azure_bluet')
    event.hide('minecraft:red_tulip')
    event.hide('minecraft:orange_tulip')
    event.hide('minecraft:white_tulip')
    event.hide('minecraft:pink_tulip')
    event.hide('minecraft:oxeye_daisy')
    event.hide('minecraft:cornflower')
    event.hide('minecraft:lily_of_the_valley')
    event.hide('minecraft:torchflower')
    event.hide('minecraft:wither_rose')
    event.hide('minecraft:pink_petals')
    event.hide('minecraft:spore_blossom')
    event.hide('minecraft:bamboo')
    event.hide('minecraft:sugar_cane')
    event.hide('minecraft:cactus')
    event.hide('minecraft:crimson_roots')
    event.hide('minecraft:warped_roots')
    event.hide('minecraft:nether_sprouts')
    event.hide('minecraft:weeping_vines')
    event.hide('minecraft:twisting_vines')
    event.hide('minecraft:vines')
    event.hide('minecraft:tall_grass')
    event.hide('minecraft:large_fern')
    event.hide('minecraft:sunflower')
    event.hide('minecraft:lilac')
    event.hide('minecraft:rose_bush')
    event.hide('minecraft:peony')
    event.hide('minecraft:pitcher_plant')
    event.hide('minecraft:big_dripleaf')
    event.hide('minecraft:small_dripleaf')
    event.hide('minecraft:chorus_plant')
    event.hide('minecraft:chorus_flower')
    event.hide('minecraft:glow_lichen')
    event.hide('minecraft:hanging_roots')
    event.hide('minecraft:frogspawn')
    event.hide('minecraft:turtle_egg')
    event.hide('minecraft:sniffer_egg')
    event.hide('minecraft:wheat_seeds')
    event.hide('minecraft:cocoa_beans')
    event.hide('minecraft:pumpkin_seeds')
    event.hide('minecraft:melon_seeds')
    event.hide('minecraft:beetroot_seeds')
    event.hide('minecraft:torchflower_seeds')
    event.hide('minecraft:pitcher_pod')
    event.hide('minecraft:glow_berries')
    event.hide('minecraft:sweet_berries')
    event.hide('minecraft:nether_wart')
    event.hide('minecraft:lily_pad')
    event.hide('minecraft:seagrass')
    event.hide('minecraft:sea_pickle')
    event.hide('minecraft:fern')

    event.hide('minecraft:tube_coral')
    event.hide('minecraft:dead_tube_coral')
    event.hide('minecraft:tube_coral_fan')
    event.hide('minecraft:dead_tube_coral_fan')
    event.hide('minecraft:tube_coral_block')
    event.hide('minecraft:dead_tube_coral_block')
    event.hide('minecraft:brain_coral')
    event.hide('minecraft:dead_brain_coral')
    event.hide('minecraft:brain_coral_fan')
    event.hide('minecraft:dead_brain_coral_fan')
    event.hide('minecraft:brain_coral_block')
    event.hide('minecraft:dead_brain_coral_block')
    event.hide('minecraft:bubble_coral')
    event.hide('minecraft:dead_bubble_coral')
    event.hide('minecraft:bubble_coral_fan')
    event.hide('minecraft:dead_bubble_coral_fan')
    event.hide('minecraft:bubble_coral_block')
    event.hide('minecraft:dead_bubble_coral_block')
    event.hide('minecraft:fire_coral')
    event.hide('minecraft:dead_fire_coral')
    event.hide('minecraft:fire_coral_fan')
    event.hide('minecraft:dead_fire_coral_fan')
    event.hide('minecraft:fire_coral_block')
    event.hide('minecraft:dead_fire_coral_block')
    event.hide('minecraft:horn_coral')
    event.hide('minecraft:dead_horn_coral')
    event.hide('minecraft:horn_coral_fan')
    event.hide('minecraft:dead_horn_coral_fan')
    event.hide('minecraft:horn_coral_block')
    event.hide('minecraft:dead_horn_coral_block')

    event.hide('minecraft:sponge')
    event.hide('minecraft:wet_sponge')
    event.hide('minecraft:melon')
    event.hide('minecraft:pumpkin')
    event.hide('minecraft:carved_pumpkin')
    event.hide('minecraft:jack_o_lantern')
    event.hide('minecraft:bee_nest')
    event.hide('minecraft:honeycomb_block')

    event.hide('minecraft:ochre_froglight')
    event.hide('minecraft:verdant_froglight')
    event.hide('minecraft:pearlescent_froglight')

    event.hide('minecraft:sculk')
    event.hide('minecraft:sculk_vein')
    event.hide('minecraft:sculk_catalyst')
    event.hide('minecraft:sculk_shrieker')
    event.hide('minecraft:sculk_sensor')

    event.hide('minecraft:soul_torch')
    event.hide('minecraft:lantern')
    event.hide('minecraft:soul_lantern')
    event.hide('minecraft:end_rod')
    // event.hide('minecraft:crafting_table') // would love to remove this also, but that removes the crafting recipe option for all recipes
    event.hide('minecraft:stonecutter')
    event.hide('minecraft:lantern')
    event.hide('minecraft:fletching_table')
    event.hide('minecraft:furnace')
    event.hide('minecraft:smoker')
    event.hide('minecraft:blast_furnace')
    event.hide('minecraft:campfire')
    event.hide('minecraft:soul_campfire')
    event.hide('minecraft:anvil')
    event.hide('minecraft:chipped_anvil')
    event.hide('minecraft:damaged_anvil')
    event.hide('minecraft:composter')
    event.hide('minecraft:beehive')
    event.hide('minecraft:suspicious_sand')
    event.hide('minecraft:suspicious_gravel')

    event.hide('minecraft:bookshelf')
    event.hide('minecraft:chest')
    event.hide('minecraft:barrel')
    event.hide('minecraft:ender_chest')
    event.hide('minecraft:respawn_anchor')
    event.hide('minecraft:enchanting_table')
    event.hide('minecraft:conduit')
    event.hide('minecraft:skeleton_skull')
    event.hide('minecraft:wither_skeleton_skull')
    event.hide('minecraft:player_head')
    event.hide('minecraft:zombie_head')
    event.hide('minecraft:creeper_head')
    event.hide('minecraft:piglin_head')
    event.hide('minecraft:dragon_head')
    event.hide('minecraft:dragon_egg')

    event.hide('minecraft:end_portal_frame')
    event.hide('minecraft:ender_eye')
    event.hide('minecraft:infested_stone')
    event.hide('minecraft:infested_cobblestone')
    event.hide('minecraft:infested_stone_bricks')
    event.hide('minecraft:infested_mossy_stone_bricks')
    event.hide('minecraft:infested_cracked_stone_bricks')
    event.hide('minecraft:infested_chiseled_stone_bricks')
    event.hide('minecraft:infested_deepslate')
    event.hide('minecraft:calibrated_sculk_sensor')
    event.hide('minecraft:trapped_chest')
    event.hide('minecraft:minecart_with_chest')
    event.hide('minecraft:minecart_with_furnace')

    event.hide('minecraft:wooden_sword')
    event.hide('minecraft:stone_sword')
    event.hide('minecraft:iron_sword')
    event.hide('minecraft:golden_sword')
    event.hide('minecraft:diamond_sword')
    event.hide('minecraft:netherite_sword')

    event.hide('minecraft:wooden_shovel')
    event.hide('minecraft:stone_shovel')
    event.hide('minecraft:iron_shovel')
    event.hide('minecraft:golden_shovel')
    event.hide('minecraft:diamond_shovel')
    event.hide('minecraft:netherite_shovel')

    event.hide('minecraft:wooden_pickaxe')
    event.hide('minecraft:stone_pickaxe')
    event.hide('minecraft:iron_pickaxe')
    event.hide('minecraft:golden_pickaxe')
    event.hide('minecraft:diamond_pickaxe')
    event.hide('minecraft:netherite_pickaxe')

    event.hide('minecraft:wooden_axe')
    event.hide('minecraft:stone_axe')
    event.hide('minecraft:iron_axe')
    event.hide('minecraft:golden_axe')
    event.hide('minecraft:diamond_axe')
    event.hide('minecraft:netherite_axe')

    event.hide('minecraft:wooden_hoe')
    event.hide('minecraft:stone_hoe')
    event.hide('minecraft:iron_hoe')
    event.hide('minecraft:golden_hoe')
    event.hide('minecraft:diamond_hoe')
    event.hide('minecraft:netherite_hoe')

    event.hide('minecraft:bucket')
    event.hide('minecraft:water_bucket')
    event.hide('minecraft:cod_bucket')
    event.hide('minecraft:salmon_bucket')
    event.hide('minecraft:tropical_fish_bucket')
    event.hide('minecraft:pufferfish_bucket')
    event.hide('minecraft:axolotl_bucket')
    event.hide('minecraft:axolotl_bucket')
    event.hide('minecraft:tadpole_bucket')
    event.hide('minecraft:lava_bucket')
    event.hide('minecraft:powder_snow_bucket')
    event.hide('minecraft:milk_bucket')
    event.hide('minecraft:fishing_rod')
    event.hide('minecraft:shears')
    event.hide('minecraft:recovery_compass')
    event.hide('minecraft:ender_pearl')
    event.hide('minecraft:elytra')
    event.hide('minecraft:firework_rocket')
    event.hide('minecraft:trident')
    event.hide('minecraft:conduit')
    
    event.hide('minecraft:iron_helmet')
    event.hide('minecraft:iron_chestplate')
    event.hide('minecraft:iron_leggings')
    event.hide('minecraft:iron_boots')
    event.hide('minecraft:golden_helmet')
    event.hide('minecraft:golden_chestplate')
    event.hide('minecraft:golden_leggings')
    event.hide('minecraft:golden_boots')
    event.hide('minecraft:diamond_helmet')
    event.hide('minecraft:diamond_chestplate')
    event.hide('minecraft:diamond_leggings')
    event.hide('minecraft:diamond_boots')

    event.hide('minecraft:turtle_helmet')
    event.hide('minecraft:iron_horse_armor')
    event.hide('minecraft:golden_horse_armor')
    event.hide('minecraft:diamond_horse_armor')

    event.hide('minecraft:totem_of_undying')

    event.hide('minecraft:apple')
    event.hide('minecraft:golden_apple')
    event.hide('minecraft:enchanted_golden_apple')
    event.hide('minecraft:melon_slice')
    event.hide('minecraft:chorus_fruit')
    event.hide('minecraft:carrot')
    event.hide('minecraft:golden_carrot')
    event.hide('minecraft:potato')
    event.hide('minecraft:baked_potato')
    event.hide('minecraft:poisonous_potato')
    event.hide('minecraft:beetroot')
    event.hide('minecraft:beef')
    event.hide('minecraft:cooked_beef')
    event.hide('minecraft:porkchop')
    event.hide('minecraft:cooked_porkchop')
    event.hide('minecraft:mutton')
    event.hide('minecraft:cooked_mutton')
    event.hide('minecraft:chicken')
    event.hide('minecraft:cooked_chicken')
    event.hide('minecraft:rabbit')
    event.hide('minecraft:cooked_rabbit')
    event.hide('minecraft:cod')
    event.hide('minecraft:cooked_cod')
    event.hide('minecraft:salmon')
    event.hide('minecraft:cooked_salmon')
    event.hide('minecraft:tropical_fish')
    event.hide('minecraft:pufferfish')
    event.hide('minecraft:bread')
    event.hide('minecraft:cookie')
    event.hide('minecraft:cake')
    event.hide('minecraft:melon_slice')
    event.hide('minecraft:spider_eye')
    event.hide('minecraft:mushroom_stew')
    event.hide('minecraft:beetroot_soup')
    event.hide('minecraft:rabbit_stew')
    event.hide('minecraft:suspicious_stew')
    event.hide('minecraft:honey_bottle')
    event.hide('minecraft:tipped_arrow')
    
    event.hide('minecraft:tipped_arrow')
    event.hide('minecraft:potion')
    event.hide('minecraft:splash_potion')
    event.hide('minecraft:lingering_potion')

    event.hide('minecraft:raw_iron')
    event.hide('minecraft:raw_copper')
    event.hide('minecraft:raw_gold')
    event.hide('minecraft:emerald')
    event.hide('minecraft:lapis_lazuli')
    event.hide('minecraft:diamond')
    event.hide('minecraft:nether_quartz')
    event.hide('minecraft:amethyst_shard')
    event.hide('minecraft:iron_nugget')
    event.hide('minecraft:gold_nugget')
    event.hide('minecraft:netherite_scrap')
    event.hide('minecraft:raw_copper')

    event.hide('minecraft:wheat')
    event.hide('minecraft:honeycomb')
    event.hide('minecraft:scute')
    event.hide('minecraft:prismarine_shard')
    event.hide('minecraft:prismarine_crystals')
    event.hide('minecraft:nautilus_shell')
    event.hide('minecraft:heart_of_the_sea')
    event.hide('minecraft:blaze_rod')
    event.hide('minecraft:blaze_powder')
    event.hide('minecraft:nether_star')
    event.hide('minecraft:shulker_shell')
    event.hide('minecraft:popped_chorus_fruit')
    event.hide('minecraft:echo_shard')
    event.hide('minecraft:disk_fragment')

    event.hide('minecraft:nether_brick')
    event.hide('minecraft:firework_star')
    event.hide('minecraft:glass_bottle')
    event.hide('minecraft:dragon_breath')
    event.hide('minecraft:fermented_spider_eye')
    event.hide('minecraft:sugar')
    event.hide('minecraft:rabbits_foot')
    event.hide('minecraft:glistering_melon_slice')
    event.hide('minecraft:magma_cream')
    event.hide('minecraft:ghast_tear')
    event.hide('minecraft:phantom_membrane')

    event.hide('minecraft:smithing_template')
    event.hide('minecraft:netherite_upgrade_smithing_template')
    event.hide('minecraft:experience_bottle')
    event.hide('minecraft:enchanted_book')

    event.hide('minecraft:spawner')

    event.hide('minecraft:beacon')

    
    event.hide('minecraft:disc_fragment_5')

    event.hide('minecraft:end_crystal')

    event.hide('create:wand_of_symmetry')

    event.hide('tfc:hand_wheel_base')
    event.hide('tfc:hand_wheel')
    event.hide('tfc:windmill_blade')
    event.hide('tfc:orange_windmill_blade')
    event.hide('tfc:magenta_windmill_blade')
    event.hide('tfc:light_blue_windmill_blade')
    event.hide('tfc:yellow_windmill_blade')
    event.hide('tfc:lime_windmill_blade')
    event.hide('tfc:pink_windmill_blade')
    event.hide('tfc:gray_windmill_blade')
    event.hide('tfc:light_gray_windmill_blade')
    event.hide('tfc:cyan_windmill_blade')
    event.hide('tfc:purple_windmill_blade')
    event.hide('tfc:blue_windmill_blade')
    event.hide('tfc:brown_windmill_blade')
    event.hide('tfc:green_windmill_blade')
    event.hide('tfc:red_windmill_blade')
    event.hide('tfc:black_windmill_blade')
    event.hide('tfc:rustic_windmill_blade')
    event.hide('tfc:lattice_windmill_blade')

    event.hide('create:zinc_nugget')
    event.hide('create:zinc_ore')
    event.hide('create:deepslate_zinc_ore')
    event.hide('create:raw_zinc_block')
    event.hide('create:zinc_block')

    event.hide('create:copper_nugget')
    event.hide('create:brass_nugget')
    event.hide('create:brass_block')

    event.hide('create:potion')
    event.hide('minecraft:brewing_stand')
    
    event.hide('create:experience_nugget')
    event.hide('create:oak_window')
    event.hide('create:oak_window_pane')
    event.hide('create:spruce_window')
    event.hide('create:spruce_window_pane')
    event.hide('create:birch_window')
    event.hide('create:birch_window_pane')
    event.hide('create:jungle_window')
    event.hide('create:jungle_window_pane')
    event.hide('create:acacia_window')
    event.hide('create:acacia_window_pane')
    event.hide('create:dark_oak_window')
    event.hide('create:dark_oak_window_pane')
    event.hide('create:mangrove_window')
    event.hide('create:mangrove_window_pane')
    event.hide('create:crimson_window')
    event.hide('create:crimson_window_pane')
    event.hide('create:warped_window')
    event.hide('create:warped_window_pane')
    event.hide('create:cherry_window')
    event.hide('create:cherry_window_pane')
    event.hide('create:bamboo_window')
    event.hide('create:bamboo_window_pane')



    event.hide('minecraft:angler_pottery_sherd')
    event.hide('minecraft:archer_pottery_sherd')
    event.hide('minecraft:arms_up_pottery_sherd')
    event.hide('minecraft:blade_pottery_sherd')
    event.hide('minecraft:brewer_pottery_sherd')
    event.hide('minecraft:burn_pottery_sherd')
    event.hide('minecraft:danger_pottery_sherd')
    event.hide('minecraft:explorer_pottery_sherd')
    event.hide('minecraft:friend_pottery_sherd')
    event.hide('minecraft:heart_pottery_sherd')
    event.hide('minecraft:heartbreak_pottery_sherd')
    event.hide('minecraft:howl_pottery_sherd')
    event.hide('minecraft:miner_pottery_sherd')
    event.hide('minecraft:mourner_pottery_sherd')
    event.hide('minecraft:plenty_pottery_sherd')
    event.hide('minecraft:prize_pottery_sherd')
    event.hide('minecraft:sheaf_pottery_sherd')
    event.hide('minecraft:shelter_pottery_sherd')
    event.hide('minecraft:skull_pottery_sherd')
    event.hide('minecraft:snort_pottery_sherd')
    event.hide('firmalife:pottery_sherd')

    
    // event.hide('integration:spawn_eggs')
    event.hide('/\\w+:\\w+_spawn_egg/')
    event.hide('/\\w+:spawn_egg/\\w+/')
    event.hide('minecraft:dried_kelp')

    event.hide('firmalife:pumping_station')
    event.hide('minecraft:brush')

    event.hide('minecraft:command_block')
    event.hide('minecraft:chain_command_block')
    event.hide('minecraft:repeating_command_block')
    event.hide('minecraft:command_block_minecart')
    event.hide('minecraft:jigsaw')
    event.hide('minecraft:structure_block')
    event.hide('minecraft:structure_void')
    event.hide('minecraft:barrier')
    event.hide('minecraft:debug_stick')
    // event.hide('minecraft:light')

    event.hide('create:handheld_worldshaper')
    event.hide('create:cinder_flour')
    event.hide('create:experience_block')

    
    event.hide('create:asurine')
    event.hide('create:cut_asurine')
    event.hide('create:cut_asurine_stairs')
    event.hide('create:cut_asurine_slab')
    event.hide('create:cut_asurine_wall')
    event.hide('create:polished_cut_asurine')
    event.hide('create:polished_cut_asurine_stairs')
    event.hide('create:polished_cut_asurine_slab')
    event.hide('create:polished_cut_asurine_wall')
    event.hide('create:cut_asurine_bricks')
    event.hide('create:cut_asurine_brick_stairs')
    event.hide('create:cut_asurine_brick_slab')
    event.hide('create:cut_asurine_brick_wall')
    event.hide('create:small_asurine_bricks')
    event.hide('create:small_asurine_brick_stairs')
    event.hide('create:small_asurine_brick_slab')
    event.hide('create:small_asurine_brick_wall')
    event.hide('create:layered_asurine')
    event.hide('create:asurine_pillar')

    event.hide('create:crimsite')
    event.hide('create:cut_crimsite')
    event.hide('create:cut_crimsite_stairs')
    event.hide('create:cut_crimsite_slab')
    event.hide('create:cut_crimsite_wall')
    event.hide('create:polished_cut_crimsite')
    event.hide('create:polished_cut_crimsite_stairs')
    event.hide('create:polished_cut_crimsite_slab')
    event.hide('create:polished_cut_crimsite_wall')
    event.hide('create:cut_crimsite_bricks')
    event.hide('create:cut_crimsite_brick_stairs')
    event.hide('create:cut_crimsite_brick_slab')
    event.hide('create:cut_crimsite_brick_wall')
    event.hide('create:small_crimsite_bricks')
    event.hide('create:small_crimsite_brick_stairs')
    event.hide('create:small_crimsite_brick_slab')
    event.hide('create:small_crimsite_brick_wall')
    event.hide('create:layered_crimsite')
    event.hide('create:crimsite_pillar')

    event.hide('create:limestone')
    event.hide('create:cut_limestone')
    event.hide('create:cut_limestone_stairs')
    event.hide('create:cut_limestone_slab')
    event.hide('create:cut_limestone_wall')
    event.hide('create:polished_cut_limestone')
    event.hide('create:polished_cut_limestone_stairs')
    event.hide('create:polished_cut_limestone_slab')
    event.hide('create:polished_cut_limestone_wall')
    event.hide('create:cut_limestone_bricks')
    event.hide('create:cut_limestone_brick_stairs')
    event.hide('create:cut_limestone_brick_slab')
    event.hide('create:cut_limestone_brick_wall')
    event.hide('create:small_limestone_bricks')
    event.hide('create:small_limestone_brick_stairs')
    event.hide('create:small_limestone_brick_slab')
    event.hide('create:small_limestone_brick_wall')
    event.hide('create:layered_limestone')
    event.hide('create:limestone_pillar')

    event.hide('create:ochrum')
    event.hide('create:cut_ochrum')
    event.hide('create:cut_ochrum_stairs')
    event.hide('create:cut_ochrum_slab')
    event.hide('create:cut_ochrum_wall')
    event.hide('create:polished_cut_ochrum')
    event.hide('create:polished_cut_ochrum_stairs')
    event.hide('create:polished_cut_ochrum_slab')
    event.hide('create:polished_cut_ochrum_wall')
    event.hide('create:cut_ochrum_bricks')
    event.hide('create:cut_ochrum_brick_stairs')
    event.hide('create:cut_ochrum_brick_slab')
    event.hide('create:cut_ochrum_brick_wall')
    event.hide('create:small_ochrum_bricks')
    event.hide('create:small_ochrum_brick_stairs')
    event.hide('create:small_ochrum_brick_slab')
    event.hide('create:small_ochrum_brick_wall')
    event.hide('create:layered_ochrum')
    event.hide('create:ochrum_pillar')

    event.hide('create:scoria')
    event.hide('create:cut_scoria')
    event.hide('create:cut_scoria_stairs')
    event.hide('create:cut_scoria_slab')
    event.hide('create:cut_scoria_wall')
    event.hide('create:polished_cut_scoria')
    event.hide('create:polished_cut_scoria_stairs')
    event.hide('create:polished_cut_scoria_slab')
    event.hide('create:polished_cut_scoria_wall')
    event.hide('create:cut_scoria_bricks')
    event.hide('create:cut_scoria_brick_stairs')
    event.hide('create:cut_scoria_brick_slab')
    event.hide('create:cut_scoria_brick_wall')
    event.hide('create:small_scoria_bricks')
    event.hide('create:small_scoria_brick_stairs')
    event.hide('create:small_scoria_brick_slab')
    event.hide('create:small_scoria_brick_wall')
    event.hide('create:layered_scoria')
    event.hide('create:scoria_pillar')

    event.hide('create:scorchia')
    event.hide('create:cut_scorchia')
    event.hide('create:cut_scorchia_stairs')
    event.hide('create:cut_scorchia_slab')
    event.hide('create:cut_scorchia_wall')
    event.hide('create:polished_cut_scorchia')
    event.hide('create:polished_cut_scorchia_stairs')
    event.hide('create:polished_cut_scorchia_slab')
    event.hide('create:polished_cut_scorchia_wall')
    event.hide('create:cut_scorchia_bricks')
    event.hide('create:cut_scorchia_brick_stairs')
    event.hide('create:cut_scorchia_brick_slab')
    event.hide('create:cut_scorchia_brick_wall')
    event.hide('create:small_scorchia_bricks')
    event.hide('create:small_scorchia_brick_stairs')
    event.hide('create:small_scorchia_brick_slab')
    event.hide('create:small_scorchia_brick_wall')
    event.hide('create:layered_scorchia')
    event.hide('create:scorchia_pillar')
    
    event.hide('create:veridium')
    event.hide('create:cut_veridium')
    event.hide('create:cut_veridium_stairs')
    event.hide('create:cut_veridium_slab')
    event.hide('create:cut_veridium_wall')
    event.hide('create:polished_cut_veridium')
    event.hide('create:polished_cut_veridium_stairs')
    event.hide('create:polished_cut_veridium_slab')
    event.hide('create:polished_cut_veridium_wall')
    event.hide('create:cut_veridium_bricks')
    event.hide('create:cut_veridium_brick_stairs')
    event.hide('create:cut_veridium_brick_slab')
    event.hide('create:cut_veridium_brick_wall')
    event.hide('create:small_veridium_bricks')
    event.hide('create:small_veridium_brick_stairs')
    event.hide('create:small_veridium_brick_slab')
    event.hide('create:small_veridium_brick_wall')
    event.hide('create:layered_veridium')
    event.hide('create:veridium_pillar')

    event.hide('create:cut_granite')
    event.hide('create:cut_granite_stairs')
    event.hide('create:cut_granite_slab')
    event.hide('create:cut_granite_wall')
    event.hide('create:polished_cut_granite')
    event.hide('create:polished_cut_granite_stairs')
    event.hide('create:polished_cut_granite_slab')
    event.hide('create:polished_cut_granite_wall')
    event.hide('create:cut_granite_bricks')
    event.hide('create:cut_granite_brick_stairs')
    event.hide('create:cut_granite_brick_slab')
    event.hide('create:cut_granite_brick_wall')
    event.hide('create:small_granite_bricks')
    event.hide('create:small_granite_brick_stairs')
    event.hide('create:small_granite_brick_slab')
    event.hide('create:small_granite_brick_wall')
    event.hide('create:layered_granite')
    event.hide('create:granite_pillar')

    event.hide('create:cut_diorite')
    event.hide('create:cut_diorite_stairs')
    event.hide('create:cut_diorite_slab')
    event.hide('create:cut_diorite_wall')
    event.hide('create:polished_cut_diorite')
    event.hide('create:polished_cut_diorite_stairs')
    event.hide('create:polished_cut_diorite_slab')
    event.hide('create:polished_cut_diorite_wall')
    event.hide('create:cut_diorite_bricks')
    event.hide('create:cut_diorite_brick_stairs')
    event.hide('create:cut_diorite_brick_slab')
    event.hide('create:cut_diorite_brick_wall')
    event.hide('create:small_diorite_bricks')
    event.hide('create:small_diorite_brick_stairs')
    event.hide('create:small_diorite_brick_slab')
    event.hide('create:small_diorite_brick_wall')
    event.hide('create:layered_diorite')
    event.hide('create:diorite_pillar')

    event.hide('create:cut_andesite')
    event.hide('create:cut_andesite_stairs')
    event.hide('create:cut_andesite_slab')
    event.hide('create:cut_andesite_wall')
    event.hide('create:polished_cut_andesite')
    event.hide('create:polished_cut_andesite_stairs')
    event.hide('create:polished_cut_andesite_slab')
    event.hide('create:polished_cut_andesite_wall')
    event.hide('create:cut_andesite_bricks')
    event.hide('create:cut_andesite_brick_stairs')
    event.hide('create:cut_andesite_brick_slab')
    event.hide('create:cut_andesite_brick_wall')
    event.hide('create:small_andesite_bricks')
    event.hide('create:small_andesite_brick_stairs')
    event.hide('create:small_andesite_brick_slab')
    event.hide('create:small_andesite_brick_wall')
    event.hide('create:layered_andesite')
    event.hide('create:andesite_pillar')

    event.hide('create:cut_calcite')
    event.hide('create:cut_calcite_stairs')
    event.hide('create:cut_calcite_slab')
    event.hide('create:cut_calcite_wall')
    event.hide('create:polished_cut_calcite')
    event.hide('create:polished_cut_calcite_stairs')
    event.hide('create:polished_cut_calcite_slab')
    event.hide('create:polished_cut_calcite_wall')
    event.hide('create:cut_calcite_bricks')
    event.hide('create:cut_calcite_brick_stairs')
    event.hide('create:cut_calcite_brick_slab')
    event.hide('create:cut_calcite_brick_wall')
    event.hide('create:small_calcite_bricks')
    event.hide('create:small_calcite_brick_stairs')
    event.hide('create:small_calcite_brick_slab')
    event.hide('create:small_calcite_brick_wall')
    event.hide('create:layered_calcite')
    event.hide('create:calcite_pillar')

    event.hide('create:cut_dripstone')
    event.hide('create:cut_dripstone_stairs')
    event.hide('create:cut_dripstone_slab')
    event.hide('create:cut_dripstone_wall')
    event.hide('create:polished_cut_dripstone')
    event.hide('create:polished_cut_dripstone_stairs')
    event.hide('create:polished_cut_dripstone_slab')
    event.hide('create:polished_cut_dripstone_wall')
    event.hide('create:cut_dripstone_bricks')
    event.hide('create:cut_dripstone_brick_stairs')
    event.hide('create:cut_dripstone_brick_slab')
    event.hide('create:cut_dripstone_brick_wall')
    event.hide('create:small_dripstone_bricks')
    event.hide('create:small_dripstone_brick_stairs')
    event.hide('create:small_dripstone_brick_slab')
    event.hide('create:small_dripstone_brick_wall')
    event.hide('create:layered_dripstone')
    event.hide('create:dripstone_pillar')

    event.hide('create:cut_deepslate')
    event.hide('create:cut_deepslate_stairs')
    event.hide('create:cut_deepslate_slab')
    event.hide('create:cut_deepslate_wall')
    event.hide('create:polished_cut_deepslate')
    event.hide('create:polished_cut_deepslate_stairs')
    event.hide('create:polished_cut_deepslate_slab')
    event.hide('create:polished_cut_deepslate_wall')
    event.hide('create:cut_deepslate_bricks')
    event.hide('create:cut_deepslate_brick_stairs')
    event.hide('create:cut_deepslate_brick_slab')
    event.hide('create:cut_deepslate_brick_wall')
    event.hide('create:small_deepslate_bricks')
    event.hide('create:small_deepslate_brick_stairs')
    event.hide('create:small_deepslate_brick_slab')
    event.hide('create:small_deepslate_brick_wall')
    event.hide('create:layered_deepslate')
    event.hide('create:deepslate_pillar')

    event.hide('create:cut_tuff')
    event.hide('create:cut_tuff_stairs')
    event.hide('create:cut_tuff_slab')
    event.hide('create:cut_tuff_wall')
    event.hide('create:polished_cut_tuff')
    event.hide('create:polished_cut_tuff_stairs')
    event.hide('create:polished_cut_tuff_slab')
    event.hide('create:polished_cut_tuff_wall')
    event.hide('create:cut_tuff_bricks')
    event.hide('create:cut_tuff_brick_stairs')
    event.hide('create:cut_tuff_brick_slab')
    event.hide('create:cut_tuff_brick_wall')
    event.hide('create:small_tuff_bricks')
    event.hide('create:small_tuff_brick_stairs')
    event.hide('create:small_tuff_brick_slab')
    event.hide('create:small_tuff_brick_wall')
    event.hide('create:layered_tuff')
    event.hide('create:tuff_pillar')




    // event.hide('tfc:wood/axle/acacia')
    // event.hide('tfc:wood/bladed_axle/acacia')
    // event.hide('tfc:wood/encased_axle/acacia')
    // event.hide('tfc:wood/clutch/acacia')
    // event.hide('tfc:wood/gear_box/acacia')
    // event.hide('tfc:wood/water_wheel/acacia')

    // event.hide('tfc:wood/axle/ash')
    // event.hide('tfc:wood/bladed_axle/ash')
    // event.hide('tfc:wood/encased_axle/ash')
    // event.hide('tfc:wood/clutch/ash')
    // event.hide('tfc:wood/gear_box/ash')
    // event.hide('tfc:wood/water_wheel/ash')

    // event.hide('tfc:wood/axle/aspen')
    // event.hide('tfc:wood/bladed_axle/aspen')
    // event.hide('tfc:wood/encased_axle/aspen')
    // event.hide('tfc:wood/clutch/aspen')
    // event.hide('tfc:wood/gear_box/aspen')
    // event.hide('tfc:wood/water_wheel/aspen')

    // event.hide('tfc:wood/axle/birch')
    // event.hide('tfc:wood/bladed_axle/birch')
    // event.hide('tfc:wood/encased_axle/birch')
    // event.hide('tfc:wood/clutch/birch')
    // event.hide('tfc:wood/gear_box/birch')
    // event.hide('tfc:wood/water_wheel/birch')

    // event.hide('tfc:wood/axle/blackwood')
    // event.hide('tfc:wood/bladed_axle/blackwood')
    // event.hide('tfc:wood/encased_axle/blackwood')
    // event.hide('tfc:wood/clutch/blackwood')
    // event.hide('tfc:wood/gear_box/blackwood')
    // event.hide('tfc:wood/water_wheel/blackwood')

    // event.hide('tfc:wood/axle/chestnut')
    // event.hide('tfc:wood/bladed_axle/chestnut')
    // event.hide('tfc:wood/encased_axle/chestnut')
    // event.hide('tfc:wood/clutch/chestnut')
    // event.hide('tfc:wood/gear_box/chestnut')
    // event.hide('tfc:wood/water_wheel/chestnut')

    // event.hide('tfc:wood/axle/douglas_fir')
    // event.hide('tfc:wood/bladed_axle/douglas_fir')
    // event.hide('tfc:wood/encased_axle/douglas_fir')
    // event.hide('tfc:wood/clutch/douglas_fir')
    // event.hide('tfc:wood/gear_box/douglas_fir')
    // event.hide('tfc:wood/water_wheel/douglas_fir')

    // event.hide('tfc:wood/axle/hickory')
    // event.hide('tfc:wood/bladed_axle/hickory')
    // event.hide('tfc:wood/encased_axle/hickory')
    // event.hide('tfc:wood/clutch/hickory')
    // event.hide('tfc:wood/gear_box/hickory')
    // event.hide('tfc:wood/water_wheel/hickory')

    // event.hide('tfc:wood/axle/kapok')
    // event.hide('tfc:wood/bladed_axle/kapok')
    // event.hide('tfc:wood/encased_axle/kapok')
    // event.hide('tfc:wood/clutch/kapok')
    // event.hide('tfc:wood/gear_box/kapok')
    // event.hide('tfc:wood/water_wheel/kapok')

    // event.hide('tfc:wood/axle/mangrove')
    // event.hide('tfc:wood/bladed_axle/mangrove')
    // event.hide('tfc:wood/encased_axle/mangrove')
    // event.hide('tfc:wood/clutch/mangrove')
    // event.hide('tfc:wood/gear_box/mangrove')
    // event.hide('tfc:wood/water_wheel/mangrove')

    // event.hide('tfc:wood/axle/maple')
    // event.hide('tfc:wood/bladed_axle/maple')
    // event.hide('tfc:wood/encased_axle/maple')
    // event.hide('tfc:wood/clutch/maple')
    // event.hide('tfc:wood/gear_box/maple')
    // event.hide('tfc:wood/water_wheel/maple')

    // event.hide('tfc:wood/axle/oak')
    // event.hide('tfc:wood/bladed_axle/oak')
    // event.hide('tfc:wood/encased_axle/oak')
    // event.hide('tfc:wood/clutch/oak')
    // event.hide('tfc:wood/gear_box/oak')
    // event.hide('tfc:wood/water_wheel/oak')

    // event.hide('tfc:wood/axle/palm')
    // event.hide('tfc:wood/bladed_axle/palm')
    // event.hide('tfc:wood/encased_axle/palm')
    // event.hide('tfc:wood/clutch/palm')
    // event.hide('tfc:wood/gear_box/palm')
    // event.hide('tfc:wood/water_wheel/palm')

    // event.hide('tfc:wood/axle/pine')
    // event.hide('tfc:wood/bladed_axle/pine')
    // event.hide('tfc:wood/encased_axle/pine')
    // event.hide('tfc:wood/clutch/pine')
    // event.hide('tfc:wood/gear_box/pine')
    // event.hide('tfc:wood/water_wheel/pine')

    // event.hide('tfc:wood/axle/rosewood')
    // event.hide('tfc:wood/bladed_axle/rosewood')
    // event.hide('tfc:wood/encased_axle/rosewood')
    // event.hide('tfc:wood/clutch/rosewood')
    // event.hide('tfc:wood/gear_box/rosewood')
    // event.hide('tfc:wood/water_wheel/rosewood')

    // event.hide('tfc:wood/axle/sequoia')
    // event.hide('tfc:wood/bladed_axle/sequoia')
    // event.hide('tfc:wood/encased_axle/sequoia')
    // event.hide('tfc:wood/clutch/sequoia')
    // event.hide('tfc:wood/gear_box/sequoia')
    // event.hide('tfc:wood/water_wheel/sequoia')

    // event.hide('tfc:wood/axle/spruce')
    // event.hide('tfc:wood/bladed_axle/spruce')
    // event.hide('tfc:wood/encased_axle/spruce')
    // event.hide('tfc:wood/clutch/spruce')
    // event.hide('tfc:wood/gear_box/spruce')
    // event.hide('tfc:wood/water_wheel/spruce')

    // event.hide('tfc:wood/axle/sycamore')
    // event.hide('tfc:wood/bladed_axle/sycamore')
    // event.hide('tfc:wood/encased_axle/sycamore')
    // event.hide('tfc:wood/clutch/sycamore')
    // event.hide('tfc:wood/gear_box/sycamore')
    // event.hide('tfc:wood/water_wheel/sycamore')

    // event.hide('tfc:wood/axle/white_cedar')
    // event.hide('tfc:wood/bladed_axle/white_cedar')
    // event.hide('tfc:wood/encased_axle/white_cedar')
    // event.hide('tfc:wood/clutch/white_cedar')
    // event.hide('tfc:wood/gear_box/white_cedar')
    // event.hide('tfc:wood/water_wheel/white_cedar')

    // event.hide('tfc:wood/axle/willow')
    // event.hide('tfc:wood/bladed_axle/willow')
    // event.hide('tfc:wood/encased_axle/willow')
    // event.hide('tfc:wood/clutch/willow')
    // event.hide('tfc:wood/gear_box/willow')
    // event.hide('tfc:wood/water_wheel/willow')



    event.hide('alekiroofs:oak_roofing')
    event.hide('alekiroofs:spruce_roofing')
    event.hide('alekiroofs:birch_roofing')
    event.hide('alekiroofs:jungle_roofing')
    event.hide('alekiroofs:acacia_roofing')
    event.hide('alekiroofs:dark_oak_roofing')
    event.hide('alekiroofs:mangrove_roofing')
    event.hide('alekiroofs:cherry_roofing')
    event.hide('alekiroofs:crimson_roofing')
    event.hide('alekiroofs:warped_roofing')
    event.hide('alekiroofs:bamboo_roofing')

    event.hide('alekiships:cannon')

    event.hide('alekiships:watercraft_frame_angled')
    event.hide('alekiships:watercraft_frame_flat')
    
})

JEIEvent.hideFluids(event => // changed onEvent here
{
    event.hide('create:potion')
    // event.hide('kubejs:potion_beer')
    // event.hide('kubejs:potion_cider')
    // event.hide('kubejs:potion_rum')
    // event.hide('kubejs:potion_sake')
    // event.hide('kubejs:potion_vodka')
    // event.hide('kubejs:potion_whiskey')
    // event.hide('kubejs:potion_corn_whiskey')
    // event.hide('kubejs:potion_rye_whiskey')

    // event.hide('kubejs:potion_strong_beer')
    // event.hide('kubejs:potion_strong_cider')
    // event.hide('kubejs:potion_strong_rum')
    // event.hide('kubejs:potion_strong_sake')
    // event.hide('kubejs:potion_strong_vodka')
    // event.hide('kubejs:potion_strong_whiskey')
    // event.hide('kubejs:potion_strong_corn_whiskey')
    // event.hide('kubejs:potion_strong_rye_whiskey')
})

JEIEvents.removeCategories(event => // changed onEvent here
{ 
    event.remove('minecraft:anvil')
    event.remove('minecraft:brewing')
    event.remove('minecraft:blasting')
    event.remove('minecraft:campfire')
    event.remove('minecraft:compostable')
    event.remove('minecraft:fuel')
    event.remove('minecraft:furnace')
    event.remove('minecraft:smithing')
    event.remove('minecraft:smoking')
    event.remove('minecraft:stonecutting')

    event.remove('create:fan_haunting')

    // added to this list by Infinity_Broken
    // event.remove('minecraft:smelting')
    // event.remove('minecraft:pickaxe')
})

